# Generated by Django 4.2.2 on 2023-06-16 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='productivity_goal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='productivity_score',
            field=models.IntegerField(blank=True),
        ),
    ]
