# Generated by Django 4.2.2 on 2023-06-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_team_member_alter_team_productivity_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='productivity_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='productivity_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
